plugins:
  babble_enabled:
    default: true
    client: true
  babble_placeholder:
    default: ""
    client: true
  babble_icon:
    default: "bullhorn"
    client: true
  babble_category_name:
    default: chat
  babble_page_size:
    default: 100
    client: true
  babble_remote_post:
    default: false
  babble_remote_url:
    default: http://example.com/api/message/add
  babble_full_page:
    default: false
    client: true
  babble_shoutbox:
    default: true
    client: true
  babble_longpress_duration:
    default: 500
    client: true
